import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import { api, post } from './api';
import ClinicalAnalysis from './ClinicalAnalysis';
import { Notify, Paged, Patient, User } from './types';
import { Badge, ConfirmModal, Empty, Modal, Pagination, Spinner } from './ui';

type Route = { name: string; patientId?: string };
type Toast = { id: number; message: string; tone: string };
const today = new Date().toISOString().slice(0, 10);
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat('es-PE', { dateStyle: 'medium' }).format(new Date(value)) : '—';

function Login({ onDone }: { onDone: (user: User) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [challenge, setChallenge] = useState<any>(); const [code, setCode] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function login(event: FormEvent) {
    event.preventDefault(); setError(''); setBusy(true);
    try { const result = await post<any>('/api/auth/login', { email, password }); if (result.authenticated) onDone(await api('/api/auth/me')); else setChallenge(result); }
    catch (reason: any) { setError(reason.message); } finally { setBusy(false); }
  }
  async function verify(event: FormEvent) {
    event.preventDefault(); setError(''); setBusy(true);
    try { await post('/api/auth/mfa/verify', { challengeToken: challenge.challengeToken, code }); onDone(await api('/api/auth/me')); }
    catch (reason: any) { setError(reason.message); } finally { setBusy(false); }
  }
  return <main className="auth-shell"><section className="auth-visual"><div className="brand-symbol">OA</div><div><span className="overline light">Plataforma clínica experimental</span><h1>Decisiones mejor informadas, seguimiento más claro.</h1><p>Clasificación radiográfica y análisis longitudinal de osteoartritis de rodilla.</p></div><small>Herramienta de investigación · No sustituye el criterio médico</small></section>
    <section className="auth-form"><div className="auth-card"><div className="mobile-brand">OA · Plataforma clínica</div><span className="overline">Acceso seguro</span><h2>{challenge ? 'Verificación administrativa' : 'Bienvenido'}</h2><p>{challenge ? 'Ingrese el código temporal de su autenticador.' : 'Ingrese sus credenciales para abrir el panel.'}</p>
      {!challenge ? <form className="form-stack" onSubmit={login}><label>Correo electrónico<input type="email" maxLength={254} value={email} onChange={(event) => setEmail(event.target.value.slice(0, 254))} autoComplete="username" required /></label><label>Contraseña<input type="password" maxLength={128} value={password} onChange={(event) => setPassword(event.target.value.slice(0, 128))} autoComplete="current-password" required /></label><button className="button primary" disabled={busy}>{busy ? 'Ingresando…' : 'Ingresar al panel'}</button></form> : <form className="form-stack" onSubmit={verify}>{challenge.enrollment && <div className="enrollment"><b>Configure su autenticador</b><code>{challenge.enrollment.secret}</code></div>}<label>Código de 6 dígitos<input inputMode="numeric" minLength={6} maxLength={6} pattern="[0-9]{6}" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, '').slice(0, 6))} autoFocus required /></label><button className="button primary" disabled={busy}>Verificar</button><button type="button" className="button secondary" onClick={() => setChallenge(undefined)}>Volver</button></form>}
      {error && <div className="alert danger-alert">{error}</div>}</div></section></main>;
}

function Metric({ label, value, detail, tone = '' }: { label: string; value: number | string; detail: string; tone?: string }) { return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }

function AdminDashboard() {
  const [data, setData] = useState<any>(); useEffect(() => { void api('/api/admin/dashboard').then(setData); }, []);
  if (!data) return <Spinner />;
  return <Page title="Resumen del sistema" subtitle="Actividad operativa sin exponer información clínica identificable."><div className="metric-grid"><Metric label="Usuarios activos" value={data.activeUsers} detail="Cuentas habilitadas" /><Metric label="Médicos" value={data.clinicians} detail="Profesionales activos" /><Metric label="Pacientes" value={data.patients} detail="Conteo agregado" /><Metric label="Inferencias activas" value={data.activeJobs} detail="En cola o ejecutándose" /><Metric label="Trabajos fallidos" value={data.failedJobs} detail="Requieren revisión" tone={data.failedJobs ? 'metric-warning' : ''} /><Metric label="Eventos 24 h" value={data.events24h} detail="Trazabilidad reciente" /></div><section className="surface info-panel"><span className="overline">Estado</span><h2>Servicios clínicos disponibles</h2><p>La administración técnica gestiona cuentas, seguridad y configuración. Los datos de pacientes permanecen en el espacio privado de cada médico responsable.</p></section></Page>;
}

type AdminUser = { id: string; email: string; displayName: string; role: string; active: boolean; professionalLicense: string | null; specialty: string | null; lastAccess: string | null };
function UserForm({ initial, onClose, onSaved, notify }: { initial?: AdminUser; onClose: () => void; onSaved: () => void; notify: Notify }) {
  const [form, setForm] = useState({ email: initial?.email ?? '', displayName: initial?.displayName ?? '', password: '', role: initial?.role ?? 'CLINICIAN', professionalLicense: initial?.professionalLicense ?? '', specialty: initial?.specialty ?? '' }); const [busy, setBusy] = useState(false);
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); try { await api(initial ? `/api/admin/users/${initial.id}` : '/api/admin/users', { method: initial ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, password: form.password || undefined }) }); notify(initial ? 'Usuario actualizado' : 'Usuario registrado', 'success'); onSaved(); onClose(); } catch (error: any) { notify(error.message, 'error'); } finally { setBusy(false); } }
  return <Modal title={initial ? 'Editar usuario' : 'Registrar usuario'} onClose={onClose}><form className="form-grid" onSubmit={save}><label>Nombre completo<input minLength={2} maxLength={100} value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value.slice(0, 100) })} required /></label><label>Correo<input type="email" maxLength={254} value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value.slice(0, 254) })} required /></label><label>Rol<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="CLINICIAN">Médico</option><option value="ADMIN">Administrador técnico</option></select></label><label>Colegiatura<input maxLength={30} value={form.professionalLicense} onChange={(event) => setForm({ ...form, professionalLicense: event.target.value.slice(0, 30) })} /></label><label>Especialidad<input maxLength={80} value={form.specialty} onChange={(event) => setForm({ ...form, specialty: event.target.value.slice(0, 80) })} /></label><label>{initial ? 'Nueva contraseña (opcional)' : 'Contraseña'}<input type="password" minLength={14} maxLength={128} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value.slice(0, 128) })} required={!initial} /></label><div className="modal-actions span"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? 'Guardando…' : 'Guardar usuario'}</button></div></form></Modal>;
}

function AdminUsers({ notify }: { notify: Notify }) {
  const [data, setData] = useState<Paged<AdminUser>>(); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [editing, setEditing] = useState<AdminUser | null | undefined>(); const [confirm, setConfirm] = useState<AdminUser>();
  const load = () => api<Paged<AdminUser>>(`/api/admin/users?page=${page}&search=${encodeURIComponent(search)}`).then(setData).catch((error) => notify(error.message, 'error'));
  useEffect(() => { void load(); }, [page, search]);
  async function toggle(user: AdminUser) { try { if (user.active) await api(`/api/admin/users/${user.id}`, { method: 'DELETE' }); else await post(`/api/admin/users/${user.id}/activate`, {}); notify(user.active ? 'Cuenta desactivada' : 'Cuenta activada', 'success'); setConfirm(undefined); void load(); } catch (error: any) { notify(error.message, 'error'); } }
  async function resetMfa(user: AdminUser) { try { await post(`/api/admin/users/${user.id}/reset-mfa`, {}); notify('MFA restablecido y sesiones revocadas', 'success'); } catch (error: any) { notify(error.message, 'error'); } }
  return <Page title="Médicos y usuarios" subtitle="Administre accesos, perfiles profesionales y seguridad." action={<button className="button primary" onClick={() => setEditing(null)}>+ Nuevo usuario</button>}><div className="toolbar"><input type="search" placeholder="Buscar por nombre, correo o especialidad" maxLength={100} value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></div><section className="surface table-card">{!data ? <Spinner /> : data.items.length === 0 ? <Empty title="No hay usuarios" detail="Registre la primera cuenta desde el botón superior." /> : <><table><thead><tr><th>Usuario</th><th>Rol</th><th>Especialidad</th><th>Estado</th><th>Último acceso</th><th aria-label="Acciones" /></tr></thead><tbody>{data.items.map((user) => <tr key={user.id}><td data-label="Usuario"><b>{user.displayName}</b><small>{user.email}</small></td><td data-label="Rol">{user.role === 'ADMIN' ? 'Administrador' : 'Médico'}</td><td data-label="Especialidad">{user.specialty ?? '—'}</td><td data-label="Estado"><Badge tone={user.active ? 'success' : 'neutral'}>{user.active ? 'Activo' : 'Inactivo'}</Badge></td><td data-label="Último acceso">{formatDate(user.lastAccess)}</td><td className="row-actions"><button className="icon-button" onClick={() => setEditing(user)} title="Editar">Editar</button>{user.role === 'ADMIN' && <button className="icon-button" onClick={() => void resetMfa(user)} title="Restablecer MFA">MFA</button>}<button className="icon-button danger-text" onClick={() => setConfirm(user)}>{user.active ? 'Desactivar' : 'Activar'}</button></td></tr>)}</tbody></table><Pagination {...data} onPage={setPage} /></>}</section>{editing !== undefined && <UserForm initial={editing ?? undefined} onClose={() => setEditing(undefined)} onSaved={load} notify={notify} />}{confirm && <ConfirmModal title={confirm.active ? 'Desactivar cuenta' : 'Activar cuenta'} detail={`${confirm.displayName} ${confirm.active ? 'perderá acceso y sus sesiones serán cerradas.' : 'podrá volver a iniciar sesión.'}`} danger={confirm.active} onClose={() => setConfirm(undefined)} action={() => void toggle(confirm)} />}</Page>;
}

function AdminAudit() {
  const [data, setData] = useState<Paged<any>>(); const [page, setPage] = useState(1); const [search, setSearch] = useState('');
  useEffect(() => { void api<Paged<any>>(`/api/admin/audit?page=${page}&search=${encodeURIComponent(search)}`).then(setData); }, [page, search]);
  return <Page title="Auditoría" subtitle="Registro inmutable de accesos, cambios y decisiones."><div className="toolbar"><input type="search" placeholder="Filtrar por actor, acción o entidad" value={search} onChange={(event) => { setSearch(event.target.value.slice(0, 100)); setPage(1); }} /></div><section className="surface table-card">{!data ? <Spinner /> : <><table><thead><tr><th>Fecha</th><th>Actor</th><th>Acción</th><th>Entidad</th><th>Detalle</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.id}><td data-label="Fecha">{formatDate(item.occurredAt)}</td><td data-label="Actor">{item.actorName ?? 'Sistema'}</td><td data-label="Acción"><Badge tone="info">{item.action}</Badge></td><td data-label="Entidad">{item.entityType}</td><td data-label="Detalle"><small>{Object.keys(item.metadata ?? {}).join(', ') || '—'}</small></td></tr>)}</tbody></table><Pagination {...data} onPage={setPage} /></>}</section></Page>;
}

function AdminSettings({ notify }: { notify: Notify }) {
  const [form, setForm] = useState({ organizationName: '', reportSubtitle: '', patientCodePrefix: 'OA' }); const [loaded, setLoaded] = useState(false);
  useEffect(() => { void api<any[]>('/api/admin/settings').then((rows) => { const org = rows.find((item) => item.key === 'organization')?.value ?? {}; const code = rows.find((item) => item.key === 'patientCode')?.value ?? {}; setForm({ organizationName: org.name ?? '', reportSubtitle: org.reportSubtitle ?? '', patientCodePrefix: code.prefix ?? 'OA' }); setLoaded(true); }); }, []);
  async function save(event: FormEvent) { event.preventDefault(); try { await api('/api/admin/settings', { method: 'PATCH', body: JSON.stringify(form) }); notify('Configuración actualizada', 'success'); } catch (error: any) { notify(error.message, 'error'); } }
  if (!loaded) return <Spinner />;
  return <Page title="Configuración" subtitle="Identidad institucional y reglas generales del entorno."><section className="surface settings-card"><form className="form-grid" onSubmit={save}><label>Nombre de la institución<input minLength={2} maxLength={100} value={form.organizationName} onChange={(event) => setForm({ ...form, organizationName: event.target.value.slice(0, 100) })} required /></label><label>Prefijo de historia clínica<input minLength={1} maxLength={8} pattern="[A-Za-z0-9]+" value={form.patientCodePrefix} onChange={(event) => setForm({ ...form, patientCodePrefix: event.target.value.toUpperCase().slice(0, 8) })} required /><small>Los nuevos códigos se generarán como {form.patientCodePrefix || 'OA'}-000001.</small></label><label className="span">Subtítulo del reporte<input minLength={2} maxLength={160} value={form.reportSubtitle} onChange={(event) => setForm({ ...form, reportSubtitle: event.target.value.slice(0, 160) })} required /></label><div className="alert info-alert span">Las claves de OpenRouter, PeruDevs y cifrado solo se administran como secretos del servidor y nunca se muestran aquí.</div><button className="button primary span">Guardar configuración</button></form></section></Page>;
}

function PatientForm({ initial, onClose, onSaved, notify }: { initial?: Patient; onClose: () => void; onSaved: (patient: Patient) => void; notify: Notify }) {
  const [form, setForm] = useState({ dni: initial?.dni ?? '', names: initial?.names ?? '', surnames: initial?.surnames ?? '', birthDate: initial?.birthDate ?? '', sex: initial?.sex ?? '', phone: initial?.phone ?? '', email: initial?.email ?? '' }); const [looking, setLooking] = useState(false); const [busy, setBusy] = useState(false);
  async function lookup() { setLooking(true); try { const value = await api<any>(`/api/patients/lookup-dni?dni=${form.dni}`); if (!value.found) notify('PeruDevs no encontró información; complete los campos manualmente', 'warning'); else { setForm({ ...form, names: value.names ?? '', surnames: value.surnames ?? '', birthDate: value.birthDate ?? '', sex: value.sex ?? '' }); notify('Datos encontrados; verifíquelos antes de guardar', 'success'); } } catch (error: any) { notify(error.message, 'error'); } finally { setLooking(false); } }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); try { const patient = await api<Patient>(initial ? `/api/patients/${initial.id}` : '/api/patients', { method: initial ? 'PATCH' : 'POST', body: JSON.stringify({ ...form, sex: form.sex || null, email: form.email || null }) }); notify(initial ? 'Paciente actualizado' : `Paciente registrado con HC ${patient.medicalRecordNumber}`, 'success'); onSaved(patient); onClose(); } catch (error: any) { notify(error.message, 'error'); } finally { setBusy(false); } }
  return <Modal title={initial ? 'Editar paciente' : 'Registrar paciente'} onClose={onClose} wide><form className="form-grid" onSubmit={save}><label>DNI<div className="field-action"><input inputMode="numeric" minLength={8} maxLength={8} pattern="[0-9]{8}" value={form.dni} onChange={(event) => setForm({ ...form, dni: event.target.value.replace(/\D/g, '').slice(0, 8) })} required /><button type="button" className="button secondary" disabled={looking || form.dni.length !== 8} onClick={lookup}>{looking ? 'Consultando…' : 'Autocompletar'}</button></div></label><label>Nombres<input minLength={2} maxLength={80} value={form.names} onChange={(event) => setForm({ ...form, names: event.target.value.slice(0, 80) })} required /></label><label>Apellidos<input minLength={2} maxLength={80} value={form.surnames} onChange={(event) => setForm({ ...form, surnames: event.target.value.slice(0, 80) })} required /></label><label>Fecha de nacimiento<input type="date" max={today} value={form.birthDate} onChange={(event) => setForm({ ...form, birthDate: event.target.value })} required /></label><label>Sexo<select value={form.sex ?? ''} onChange={(event) => setForm({ ...form, sex: event.target.value as any })}><option value="">No registrado</option><option value="female">Femenino</option><option value="male">Masculino</option></select></label><label>Celular<input inputMode="numeric" minLength={9} maxLength={9} pattern="9[0-9]{8}" placeholder="9XXXXXXXX" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value.replace(/\D/g, '').slice(0, 9) })} required /></label><label>Correo opcional<input type="email" maxLength={254} value={form.email ?? ''} onChange={(event) => setForm({ ...form, email: event.target.value.slice(0, 254) })} /></label>{!initial && <div className="auto-code"><span>Historia clínica</span><b>Se generará automáticamente</b><small>No tendrá que escribir ni recordar una numeración manual.</small></div>}<div className="modal-actions span"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? 'Guardando…' : 'Guardar paciente'}</button></div></form></Modal>;
}

function ClinicianDashboard({ navigate }: { navigate: (route: Route) => void }) {
  const [data, setData] = useState<any>(); useEffect(() => { void api('/api/patients/dashboard').then(setData); }, []); if (!data) return <Spinner />;
  return <Page title="Buenos días" subtitle="Este es el estado de su actividad clínica."><div className="metric-grid four"><Metric label="Mis pacientes" value={data.patients} detail="Pacientes activos" /><Metric label="Estudios" value={data.studies} detail="Radiografías registradas" /><Metric label="Revisiones pendientes" value={data.pending} detail="Clasificaciones por confirmar" tone={data.pending ? 'metric-warning' : ''} /><Metric label="Reportes" value={data.reports} detail="Borradores generados" /></div><div className="quick-grid"><button onClick={() => navigate({ name: 'patients' })}><span>+</span><b>Registrar o buscar paciente</b><small>Inicie desde la ficha clínica.</small></button><button onClick={() => navigate({ name: 'reviews' })}><span>✓</span><b>Revisiones pendientes</b><small>Confirme resultados KL.</small></button><button onClick={() => navigate({ name: 'reports' })}><span>↗</span><b>Reportes recientes</b><small>Consulte borradores generados.</small></button></div></Page>;
}

function PatientsPage({ navigate, notify }: { navigate: (route: Route) => void; notify: Notify }) {
  const [data, setData] = useState<Paged<Patient>>(); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [modal, setModal] = useState(false);
  const load = () => api<Paged<Patient>>(`/api/patients?page=${page}&search=${encodeURIComponent(search)}`).then(setData).catch((error) => notify(error.message, 'error'));
  useEffect(() => { void load(); }, [page, search]);
  return <Page title="Mis pacientes" subtitle="Solo se muestran los pacientes registrados bajo su responsabilidad." action={<button className="button primary" onClick={() => setModal(true)}>+ Registrar paciente</button>}><div className="toolbar"><input type="search" placeholder="Buscar por nombre, DNI o historia clínica" value={search} onChange={(event) => { setSearch(event.target.value.slice(0, 100)); setPage(1); }} /></div><section className="surface table-card">{!data ? <Spinner /> : data.items.length === 0 ? <Empty title="Aún no tiene pacientes" detail="Registre un paciente para comenzar un estudio." /> : <><table><thead><tr><th>Paciente</th><th>Historia clínica</th><th>DNI</th><th>Celular</th><th>Registro</th><th /></tr></thead><tbody>{data.items.map((patient) => <tr key={patient.id}><td data-label="Paciente"><b>{patient.surnames}, {patient.names}</b><small>{patient.email ?? 'Sin correo'}</small></td><td data-label="Historia clínica"><Badge tone="info">{patient.medicalRecordNumber}</Badge></td><td data-label="DNI">••••{patient.dni.slice(-4)}</td><td data-label="Celular">{patient.phone}</td><td data-label="Registro">{formatDate(patient.createdAt)}</td><td className="row-actions"><button className="button table-action" onClick={() => navigate({ name: 'patient', patientId: patient.id })}>Ver ficha</button></td></tr>)}</tbody></table><Pagination {...data} onPage={setPage} /></>}</section>{modal && <PatientForm onClose={() => setModal(false)} notify={notify} onSaved={(patient) => { void load(); navigate({ name: 'patient', patientId: patient.id }); }} />}</Page>;
}

function PatientDetail({ id, navigate, notify }: { id: string; navigate: (route: Route) => void; notify: Notify }) {
  const [patient, setPatient] = useState<Patient>(); const [episodes, setEpisodes] = useState<any[]>([]); const [reports, setReports] = useState<any[]>([]); const [editing, setEditing] = useState(false); const [archiving, setArchiving] = useState(false);
  const load = async () => { try { const [p, e, r] = await Promise.all([api<Patient>(`/api/patients/${id}`), api<any[]>(`/api/patients/${id}/episodes`), api<any[]>(`/api/patients/${id}/reports`)]); setPatient(p); setEpisodes(e); setReports(r); } catch (error: any) { notify(error.message, 'error'); } };
  useEffect(() => { void load(); }, [id]); if (!patient) return <Spinner />;
  async function archive() { try { await api(`/api/patients/${id}`, { method: 'DELETE' }); notify('Paciente archivado', 'success'); navigate({ name: 'patients' }); } catch (error: any) { notify(error.message, 'error'); } }
  async function generate(episodeId: string, reportType: string) { try { const result = await post<any>(`/api/episodes/${episodeId}/reports`, { reportType }); notify('Reporte generado', 'success'); window.open(`/api/reports/${result.id}/download`, '_blank', 'noopener'); void load(); } catch (error: any) { notify(error.message, 'error'); } }
  return <Page title={`${patient.surnames}, ${patient.names}`} subtitle={`${patient.medicalRecordNumber} · Médico responsable actual`} action={<div className="head-actions"><button className="button secondary" onClick={() => setEditing(true)}>Editar</button><button className="button primary" onClick={() => navigate({ name: 'analysis', patientId: id })}>+ Nuevo análisis</button><button className="button danger-soft" onClick={() => setArchiving(true)}>Archivar</button></div>}><div className="profile-grid"><section className="surface identity-card"><div className="avatar">{patient.names[0]}{patient.surnames[0]}</div><div><span className="overline">Datos personales</span><h2>{patient.names} {patient.surnames}</h2><dl><div><dt>DNI</dt><dd>{patient.dni}</dd></div><div><dt>Nacimiento</dt><dd>{formatDate(patient.birthDate)}</dd></div><div><dt>Sexo</dt><dd>{patient.sex === 'female' ? 'Femenino' : patient.sex === 'male' ? 'Masculino' : 'No registrado'}</dd></div><div><dt>Celular</dt><dd>{patient.phone}</dd></div><div><dt>Correo</dt><dd>{patient.email ?? 'No registrado'}</dd></div></dl></div></section><div className="mini-metrics"><Metric label="Episodios" value={patient.stats?.episodes ?? 0} detail="Consultas registradas" /><Metric label="Estudios" value={patient.stats?.studies ?? 0} detail="Radiografías" /><Metric label="Reportes" value={patient.stats?.reports ?? 0} detail="Borradores" /></div></div>
    <section className="surface timeline-card"><div className="section-head"><div><span className="overline">Historia clínica</span><h2>Línea de tiempo</h2></div></div>{episodes.length === 0 ? <Empty title="Sin episodios" detail="Inicie un nuevo análisis para crear el primer episodio." /> : <div className="timeline">{episodes.map((episode) => <article key={episode.id}><i /><div><b>{formatDate(episode.openedAt)}</b><p>{episode.studyCount} estudio(s) · {episode.reportCount} reporte(s)</p></div><div className="row-actions"><button className="button table-action" disabled={!episode.studyCount} onClick={() => void generate(episode.id, 'EPISODE')}>PDF episodio</button><button className="button table-action" disabled={!episode.studyCount} onClick={() => void generate(episode.id, 'LONGITUDINAL')}>PDF longitudinal</button></div></article>)}</div>}</section>
    {reports.length > 0 && <section className="surface report-card"><div className="section-head"><div><span className="overline">Documentos</span><h2>Últimos 10 reportes</h2></div></div><div className="report-list">{reports.map((report) => <article key={report.id}><div><Badge tone="info">{report.reportType === 'LONGITUDINAL' ? 'Longitudinal' : 'Episodio'}</Badge><b>Episodio del {formatDate(report.episodeDate)}</b><small>Generado {formatDate(report.generatedAt)}</small></div><a className="button table-action" href={`/api/reports/${report.id}/download`}>Descargar PDF</a></article>)}</div></section>}
    {editing && <PatientForm initial={patient} onClose={() => setEditing(false)} notify={notify} onSaved={(updated) => { setPatient(updated); void load(); }} />}{archiving && <ConfirmModal title="Archivar paciente" detail="El paciente dejará de aparecer en su lista activa. Sus estudios y auditoría no se eliminarán." danger onClose={() => setArchiving(false)} action={() => void archive()} />}</Page>;
}

function SimplePagedPage({ kind, navigate }: { kind: 'studies' | 'reviews' | 'reports'; navigate: (route: Route) => void }) {
  const [data, setData] = useState<Paged<any>>(); const [page, setPage] = useState(1); useEffect(() => { void api<Paged<any>>(`/api/${kind}?page=${page}`).then(setData); }, [kind, page]);
  const title = kind === 'studies' ? 'Estudios' : kind === 'reviews' ? 'Revisiones clínicas' : 'Reportes'; const subtitle = kind === 'studies' ? 'Radiografías y estado de procesamiento.' : kind === 'reviews' ? 'Clasificaciones KL generadas y su decisión médica.' : 'Borradores del episodio y longitudinales.';
  return <Page title={title} subtitle={subtitle}><section className="surface table-card">{!data ? <Spinner /> : data.items.length === 0 ? <Empty title={`Sin ${title.toLowerCase()}`} detail="Los nuevos registros aparecerán aquí." /> : <><table><thead><tr><th>Paciente</th><th>HC</th><th>Fecha</th><th>{kind === 'reviews' ? 'Resultado' : 'Tipo / estado'}</th><th /></tr></thead><tbody>{data.items.map((item) => <tr key={item.id}><td data-label="Paciente"><b>{item.patientName}</b></td><td data-label="HC">{item.medicalRecordNumber}</td><td data-label="Fecha">{formatDate(item.examDate ?? item.episodeDate ?? item.generatedAt)}</td><td data-label="Estado">{kind === 'reviews' ? <Badge tone={item.decision ? 'success' : 'warning'}>{item.decision ?? 'Pendiente'} · KL {item.confirmedKl ?? item.probabilities?.predictedKl}</Badge> : kind === 'reports' ? item.reportType : <Badge tone="info">{item.status}</Badge>}</td><td className="row-actions">{kind === 'reports' ? <a className="button table-action" href={`/api/reports/${item.id}/download`}>Descargar</a> : <button className="button table-action" onClick={() => navigate({ name: 'patient', patientId: item.patientId })}>Ver paciente</button>}</td></tr>)}</tbody></table><Pagination {...data} onPage={setPage} /></>}</section></Page>;
}

function Page({ title, subtitle, action, children }: { title: string; subtitle: string; action?: ReactNode; children: ReactNode }) { return <div className="page"><header className="page-head"><div><span className="overline">Panel OA</span><h1>{title}</h1><p>{subtitle}</p></div>{action}</header>{children}</div>; }

function Shell({ user, onLogout, notify }: { user: User; onLogout: () => void; notify: Notify }) {
  const [route, setRoute] = useState<Route>({ name: 'dashboard' }); const [collapsed, setCollapsed] = useState(false);
  const nav = user.role === 'ADMIN' ? [['dashboard', 'Resumen', '⌂'], ['users', 'Médicos y usuarios', 'U'], ['audit', 'Auditoría', 'A'], ['settings', 'Configuración', '⚙']] : [['dashboard', 'Inicio', '⌂'], ['patients', 'Mis pacientes', 'P'], ['studies', 'Estudios', 'E'], ['reviews', 'Revisiones', 'R'], ['reports', 'Reportes', 'D']];
  const content = useMemo(() => {
    if (user.role === 'ADMIN') { if (route.name === 'users') return <AdminUsers notify={notify} />; if (route.name === 'audit') return <AdminAudit />; if (route.name === 'settings') return <AdminSettings notify={notify} />; return <AdminDashboard />; }
    if (route.name === 'patients') return <PatientsPage navigate={setRoute} notify={notify} />;
    if (route.name === 'patient' && route.patientId) return <PatientDetail id={route.patientId} navigate={setRoute} notify={notify} />;
    if (route.name === 'analysis' && route.patientId) return <AnalysisLoader patientId={route.patientId} notify={notify} onDone={() => setRoute({ name: 'patient', patientId: route.patientId })} />;
    if (['studies', 'reviews', 'reports'].includes(route.name)) return <SimplePagedPage kind={route.name as any} navigate={setRoute} />;
    return <ClinicianDashboard navigate={setRoute} />;
  }, [route, user.role]);
  return <div className={`app-shell ${collapsed ? 'collapsed' : ''}`}><aside><div className="sidebar-brand"><div className="brand-symbol small">OA</div><div><b>OA Clínica</b><small>Plataforma experimental</small></div></div><nav>{nav.map(([name, label, icon]) => <button key={name} className={route.name === name || (name === 'patients' && ['patient', 'analysis'].includes(route.name)) ? 'active' : ''} onClick={() => setRoute({ name })}><i>{icon}</i><span>{label}</span></button>)}</nav><div className="sidebar-foot"><div className="user-chip"><div>{user.displayName.slice(0, 2).toUpperCase()}</div><span><b>{user.displayName}</b><small>{user.role === 'ADMIN' ? 'Administrador técnico' : 'Médico responsable'}</small></span></div><button className="nav-logout" onClick={onLogout}><i>↪</i><span>Cerrar sesión</span></button></div></aside><main className="main-area"><div className="topbar"><button className="menu-toggle" onClick={() => setCollapsed(!collapsed)}>☰</button><div className="topbar-status"><span className="status-dot" /> Servicios operativos</div></div><div className="content">{content}</div></main></div>;
}

function AnalysisLoader({ patientId, notify, onDone }: { patientId: string; notify: Notify; onDone: () => void }) { const [patient, setPatient] = useState<Patient>(); useEffect(() => { void api<Patient>(`/api/patients/${patientId}`).then(setPatient).catch((error) => notify(error.message, 'error')); }, [patientId]); return patient ? <ClinicalAnalysis patient={patient} notify={notify} onDone={onDone} /> : <Spinner />; }

export default function App() {
  const [user, setUser] = useState<User>(); const [checking, setChecking] = useState(true); const [toasts, setToasts] = useState<Toast[]>([]);
  useEffect(() => { void api<User>('/api/auth/me').then(setUser).catch(() => undefined).finally(() => setChecking(false)); }, []);
  const notify: Notify = (message, tone = 'info') => { const id = Date.now() + Math.random(); setToasts((items) => [...items, { id, message, tone }]); window.setTimeout(() => setToasts((items) => items.filter((item) => item.id !== id)), 4500); };
  async function logout() { await post('/api/auth/logout', {}); setUser(undefined); }
  if (checking) return <div className="boot"><div className="brand-symbol">OA</div><Spinner /></div>;
  return <>{user ? <Shell user={user} notify={notify} onLogout={() => void logout()} /> : <Login onDone={setUser} />}<div className="toast-stack" aria-live="polite">{toasts.map((toast) => <div key={toast.id} className={`toast toast-${toast.tone}`}><i />{toast.message}<button onClick={() => setToasts((items) => items.filter((item) => item.id !== toast.id))}>×</button></div>)}</div></>;
}
